<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
$caller=require_auth();$ctx=user_context();$body=input_json();
$name=trim((string)($body['name']??''));$args=is_array($body['body']??null)?$body['body']:[];
function fn_require_master(array $ctx):void{if(($ctx['role']??'')!=='master')out(['data'=>null,'error'=>['message'=>'Somente o MASTER pode executar esta função.']],403);}
function fn_ensure_cron_key():string{global $config;$key=trim((string)($config['cron_key']??''));if($key!=='')return$key;$key=bin2hex(random_bytes(32));$config['cron_key']=$key;$file=__DIR__.'/config.local.php';$php="<?php\nreturn ".var_export($config,true).";\n";if(file_put_contents($file,$php,LOCK_EX)===false)throw new RuntimeException('Não foi possível salvar a chave do CRON em api/config.local.php.');@chmod($file,0640);return$key;}
function fn_base_url():string{$https=(!empty($_SERVER['HTTPS'])&&strtolower((string)$_SERVER['HTTPS'])!=='off')||(string)($_SERVER['HTTP_X_FORWARDED_PROTO']??'')==='https';$scheme=$https?'https':'http';$host=trim((string)($_SERVER['HTTP_HOST']??'escaladeproposito.com.br'));if($host==='')$host='escaladeproposito.com.br';return$scheme.'://'.$host;}
function fn_system_cron_config(array $ctx):never{fn_require_master($ctx);$key=fn_ensure_cron_key();$url=fn_base_url().'/api/cron-runner.php?key='.rawurlencode($key);$command="curl -fsS ".escapeshellarg($url)." >/dev/null 2>&1";$full="* * * * * ".$command;out(['data'=>['success'=>true,'url'=>$url,'command'=>$command,'full_line'=>$full,'schedule'=>'* * * * *'],'error'=>null]);}
function fn_admin_update_user(array $ctx,array $args):never{fn_require_master($ctx);$uid=trim((string)($args['user_id']??$args['id']??''));if($uid==='')throw new RuntimeException('Usuário não informado.');if(isset($args['role'])){$role=trim((string)$args['role']);$allowed=['master','admin','secretaria','lider','voluntario'];if(!in_array($role,$allowed,true))throw new RuntimeException('Cargo inválido.');$q=db()->prepare('SELECT id FROM user_roles WHERE user_id=? LIMIT 1');$q->execute([$uid]);$rid=$q->fetchColumn();if($rid)db()->prepare('UPDATE user_roles SET role=? WHERE id=?')->execute([$role,$rid]);else db()->prepare('INSERT INTO user_roles(id,user_id,role) VALUES(?,?,?)')->execute([uuid4(),$uid,$role]);}$pf=[];foreach(['nome','whatsapp','telefone','igreja_id','avatar_url']as$f)if(array_key_exists($f,$args))$pf[$f]=$args[$f];if($pf){$sets=[];$vals=[];foreach($pf as$k=>$v){$sets[]=$k.'=?';$vals[]=$v===''?null:$v;}$vals[]=$uid;db()->prepare('UPDATE profiles SET '.implode(',',$sets).',updated_at=NOW() WHERE id=?')->execute($vals);}out(['data'=>['success'=>true,'user_id'=>$uid],'error'=>null]);}
try{switch($name){case'system-cron-config':fn_system_cron_config($ctx);case'admin-update-user':fn_admin_update_user($ctx,$args);case'notify-leader':if(is_file(__DIR__.'/scale-response-notify.php'))out(['data'=>null,'error'=>['message'=>'Use o endpoint de notificação do líder.']],400);throw new RuntimeException('Módulo de notificação do líder não disponível.');case'send-whatsapp':case'send-post-quiz':case'test-whatsapp':case'send-whatsapp-otp':case'verify-whatsapp-otp':case'buscar-musica':out(['data'=>null,'error'=>['message'=>'Função '.$name.' ainda não está habilitada neste clone.']],400);default:out(['data'=>null,'error'=>['message'=>'Função interna não reconhecida: '.$name]],400);}}catch(Throwable$e){out(['data'=>null,'error'=>['message'=>$e->getMessage()]],500);}
