from pathlib import Path
root=Path('pkg')

def one(s,a,b,label):
    if s.count(a)!=1: raise SystemExit(f'{label}: {s.count(a)}')
    return s.replace(a,b,1)

# API: Master-only structural edit of a complete scale group.
p=root/'api'/'master-scales.php'; s=p.read_text(encoding='utf-8')
s=one(s,"if((string)($ctx['role']??'')!=='master')out(['data'=>null,'error'=>['message'=>'Somente o MASTER pode excluir escalas completas.']],403);","if((string)($ctx['role']??'')!=='master')out(['data'=>null,'error'=>['message'=>'Somente o MASTER pode gerenciar escalas completas.']],403);",'master guard')
anchor="function mse_delq(string $sql,array $a,array &$o,string $key): void"
insert="""function mse_valid_time(string $t): ?string {$t=trim($t);if($t==='')return null;if(!preg_match('/^(?:[01]\\d|2[0-3]):[0-5]\\d$/',$t))throw new RuntimeException('Horário inválido. Use HH:MM.');return$t.':00';}\nfunction mse_edit_group(string $ig,string $date,?string $cultoId,string $newDate,string $newName,?string $newTime,array $before): array {$newName=trim($newName);if($newName==='')throw new RuntimeException('Informe o nome da escala/culto.');$oldName=trim((string)($before['culto_nome']??''));$oldTime=substr((string)($before['horario']??''),0,5);$newHm=$newTime?substr($newTime,0,5):'';$clone=$cultoId===null||$cultoId===''||$newName!==$oldName||$newHm!==$oldTime;$target=$cultoId;$pdo=db();$pdo->beginTransaction();try{if($clone){$target=uuid4();$q=$pdo->prepare(\"INSERT INTO cultos(created_at,dia_semana,horario,id,igreja_id,nome,recorrente) VALUES(NOW(),NULL,?,?,?,?,0)\");$q->execute([$newTime,$target,$ig,$newName]);}elseif($newDate!==$date){$a=[$ig,$newDate];$w=\"BINARY igreja_id=BINARY ? AND data=?\";if($target===null||$target==='')$w.=\" AND culto_id IS NULL\";else{$w.=\" AND BINARY culto_id=BINARY ?\";$a[]=$target;}$q=$pdo->prepare(\"SELECT COUNT(*) FROM escalas WHERE {$w}\");$q->execute($a);if((int)$q->fetchColumn()>0)throw new RuntimeException('Já existe uma escala desse culto na nova data.');}$a=[];$w=mse_group_where($ig,$date,$cultoId,$a);$sql=$clone?\"UPDATE escalas e SET e.data=?,e.culto_id=? WHERE {$w}\":\"UPDATE escalas e SET e.data=? WHERE {$w}\";$args=$clone?array_merge([$newDate,$target],$a):array_merge([$newDate],$a);$q=$pdo->prepare($sql);$q->execute($args);$n=$q->rowCount();if($n<1)throw new RuntimeException('A escala selecionada não existe mais. Atualize a lista.');$pdo->commit();}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}$after=mse_one($ig,$newDate,$target);return['before'=>$before,'after'=>$after,'updated_departments'=>$n,'culto_isolated'=>$clone];}\n"""
s=one(s,anchor,insert+anchor,'api helpers')
old=" if($action!=='delete')throw new RuntimeException('Ação inválida.');\n $ig=trim((string)($b['igreja_id']??''));$date=mse_valid_date(trim((string)($b['data']??'')),'Data da escala');$cultoRaw=$b['culto_id']??null;$cultoId=$cultoRaw===null||trim((string)$cultoRaw)===''?null:trim((string)$cultoRaw);\n if($ig===''||$date==='')throw new RuntimeException('Escala inválida.');$row=mse_one($ig,$date,$cultoId);if(!$row)throw new RuntimeException('A escala selecionada não existe mais. Atualize a lista.');\n if(trim((string)($b['confirmation']??''))!=='EXCLUIR')throw new RuntimeException('Digite EXCLUIR para confirmar a exclusão.');"
new=" $ig=trim((string)($b['igreja_id']??''));$date=mse_valid_date(trim((string)($b['data']??'')),'Data da escala');$cultoRaw=$b['culto_id']??null;$cultoId=$cultoRaw===null||trim((string)$cultoRaw)===''?null:trim((string)$cultoRaw);\n if($ig===''||$date==='')throw new RuntimeException('Escala inválida.');$row=mse_one($ig,$date,$cultoId);if(!$row)throw new RuntimeException('A escala selecionada não existe mais. Atualize a lista.');\n if($action==='edit'){$nd=mse_valid_date(trim((string)($b['new_date']??'')),'Nova data');if($nd==='')throw new RuntimeException('Informe a nova data.');$nn=trim((string)($b['new_name']??''));$nt=mse_valid_time(trim((string)($b['new_time']??'')));$ed=mse_edit_group($ig,$date,$cultoId,$nd,$nn,$nt,$row);try{audit((string)($caller['id']??''),'master_edit_complete_scale','escalas',['igreja_id'=>$ig,'before'=>['data'=>$date,'culto_id'=>$cultoId,'nome'=>$row['culto_nome']??null,'horario'=>$row['horario']??null],'after'=>['data'=>$nd,'culto_id'=>$ed['after']['culto_id']??null,'nome'=>$ed['after']['culto_nome']??$nn,'horario'=>$ed['after']['horario']??$nt]],'warning');}catch(Throwable$e){}out(['data'=>['success'=>true,'edited'=>$ed],'error'=>null]);}\n if($action!=='delete')throw new RuntimeException('Ação inválida.');\n if(trim((string)($b['confirmation']??''))!=='EXCLUIR')throw new RuntimeException('Digite EXCLUIR para confirmar a exclusão.');"
s=one(s,old,new,'api action')
p.write_text(s,encoding='utf-8')

# Master screen: Edit + Delete.
p=root/'master-escalas.html'; h=p.read_text(encoding='utf-8')
h=h.replace('<title>Excluir escalas — MASTER</title>','<title>Gerenciar escalas — MASTER</title>',1)
h=one(h,'</style>','.edit{background:#eef4ff;color:#2458a6;border:1px solid #c9daf7}.modal{position:fixed;inset:0;background:#17203399;display:none;align-items:center;justify-content:center;padding:16px;z-index:50}.modal.open{display:flex}.dialog{width:min(520px,100%);background:#fff;border-radius:18px;padding:18px;box-shadow:0 24px 80px #0004}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{display:grid;gap:5px}.field.full{grid-column:1/-1}.field label{font-weight:800}.dialog-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:16px}@media(max-width:560px){.grid{grid-template-columns:1fr}.field.full{grid-column:auto}}</style>','style')
h=one(h,'<h1>🗑️ Excluir escala completa</h1><div class="muted">Exclusivo do MASTER. Cada linha representa uma escala completa separada por igreja, data e culto.</div><div class="note"><b>Exclusão isolada.</b> Se no mesmo dia existirem “Culto” e “Culto da Família”, excluir “Culto” remove somente aquela escala completa. A outra permanece intacta.</div>','<h1>🗓️ Gerenciar escalas completas</h1><div class="muted">Exclusivo do MASTER. Edite ou exclua uma escala completa.</div><div class="note"><b>Somente o Master</b> pode corrigir nome, data e horário depois da criação. Pessoas, funções e confirmações permanecem intactas.</div>','hero')
h=one(h,'<button class="btn danger del" ${busy?\'disabled\':\'\'}>Excluir escala completa</button>','<button class="btn edit edt" ${busy?\'disabled\':\'\'}>✏️ Editar</button> <button class="btn danger del" ${busy?\'disabled\':\'\'}>Excluir escala completa</button>','buttons')
h=one(h,"document.querySelectorAll('.del').forEach((b,idx)=>b.addEventListener('click',()=>remove(rows[idx])))","document.querySelectorAll('.edt').forEach((b,idx)=>b.addEventListener('click',()=>openEdit(rows[idx])));document.querySelectorAll('.del').forEach((b,idx)=>b.addEventListener('click',()=>remove(rows[idx])))",'edit binding')
h=one(h,"let data={churches:[],scales:[]},busy=false;","let data={churches:[],scales:[]},busy=false,editing=null;",'state')
modal='''<div class="modal" id="editModal"><div class="dialog"><h2>✏️ Editar escala completa</h2><div class="grid"><div class="field full"><label>Nome da escala / culto</label><input id="editName" maxlength="255"></div><div class="field"><label>Data</label><input id="editDate" type="date"></div><div class="field"><label>Horário</label><input id="editTime" type="time"></div></div><div class="dialog-actions"><button class="btn" id="cancelEdit">Cancelar</button><button class="btn primary" id="saveEdit">Salvar alterações</button></div></div></div>'''
h=one(h,'</main><script>','</main>'+modal+'<script>','modal')
anchor='async function remove(x){'
editjs="""function openEdit(x){editing=x;$('editName').value=(x.culto_nome&&x.culto_nome!=='Escala sem culto')?x.culto_nome:'';$('editDate').value=x.data||'';$('editTime').value=x.horario?String(x.horario).slice(0,5):'';$('editModal').classList.add('open')}function closeEdit(){if(!busy){editing=null;$('editModal').classList.remove('open')}}async function saveEdit(){if(!editing||busy)return;const name=$('editName').value.trim(),date=$('editDate').value,time=$('editTime').value;if(!name||!date){alert('Informe nome e data.');return}if(!confirm(`Editar esta escala completa?\\n\\n${editing.culto_nome||'Escala'} ${fmt(editing.data)} → ${name} ${fmt(date)} ${time}`))return;busy=true;try{await api({action:'edit',igreja_id:editing.igreja_id,data:editing.data,culto_id:editing.culto_id,new_name:name,new_date:date,new_time:time});closeEdit();msg('Escala alterada. Pessoas, funções e confirmações foram preservadas.','ok');await load()}catch(e){msg(e.message,'err')}finally{busy=false;render()}}"""
h=one(h,anchor,editjs+anchor,'edit functions')
h=one(h,"$('search').addEventListener('input',render);load();","$('search').addEventListener('input',render);$('cancelEdit').addEventListener('click',closeEdit);$('saveEdit').addEventListener('click',saveEdit);$('editModal').addEventListener('click',e=>{if(e.target===$('editModal'))closeEdit()});load();",'listeners')
p.write_text(h,encoding='utf-8')

(root/'VERSION').write_text('1.4.56\n',encoding='utf-8')
(root/'ATUALIZACAO-v1.4.56.md').write_text('''# Escala de Propósito v1.4.56 — Editar escala pelo Master\n\n- Em **Master → Gerenciar escalas**, adiciona **Editar escala** ao lado de Excluir.\n- Só o **MASTER** pode alterar **nome da escala/culto, data e horário** depois da criação.\n- Pastor/Admin, Líder, Secretária e Voluntário continuam sem essa permissão.\n- Pessoas, funções, confirmações, repertório e demais dados da escala são preservados.\n- Alterar nome ou horário isola somente aquela escala, sem modificar outros cultos de outras datas que usam o mesmo cadastro.\n- A alteração fica registrada em auditoria como `master_edit_complete_scale`.\n''',encoding='utf-8')
