<?php
declare(strict_types=1);
/** Escala de Propósito v1.4.34 — menu de consultas do voluntário via WhatsApp. */
require_once __DIR__.'/whatsapp_scale_message_v1421.php';

function v1434_is_menu_state(string $state): bool { return in_array($state,['vmenu_home','vmenu_scales','vmenu_music','vmenu_detail'],true); }
function v1434_profile_ids(array $profiles): array { return array_values(array_unique(array_filter(array_map(static fn($p)=>(string)($p['id']??''),$profiles)))); }
function v1434_igreja_id(array $profiles): string { foreach($profiles as$p){$x=trim((string)($p['igreja_id']??''));if($x!=='')return$x;}return''; }
function v1434_home_text(): string { return "✅ *Você não possui pendências para responder.*\n\n📲 *Menu do voluntário*\n\n*1* - 📅 Consultar minhas escalas confirmadas dos próximos 30 dias\n*2* - 🎵 Consultar repertório das minhas próximas escalas\n\n_Responda somente com 1 ou 2._"; }
function v1434_confirmed_scales(array $profiles): array {
    $ids=v1434_profile_ids($profiles); if(!$ids)return[];$ph=implode(',',array_fill(0,count($ids),'?'));
    try{$q=db()->prepare("SELECT ei.id item_id,ei.escala_id,ei.voluntario_id,ei.funcao,ei.status_confirmacao,e.data,e.igreja_id,e.culto_id,c.nome culto_nome,c.horario,d.nome departamento_nome FROM escala_itens ei JOIN escalas e ON BINARY e.id=BINARY ei.escala_id LEFT JOIN cultos c ON BINARY c.id=BINARY e.culto_id LEFT JOIN departamentos d ON BINARY d.id=BINARY e.departamento_id WHERE ei.voluntario_id IN ($ph) AND ei.status_confirmacao='confirmado' AND e.data BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 30 DAY) ORDER BY e.data ASC,c.horario ASC,d.nome ASC,ei.funcao ASC");$q->execute($ids);$rows=$q->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable$e){if(function_exists('v1311p_trace'))v1311p_trace('v1434_confirmed_query_error',['message'=>substr($e->getMessage(),0,240)]);return[];}
    $out=[];$seen=[];foreach($rows as$r){$key=(string)($r['item_id']??'');if($key===''||isset($seen[$key]))continue;$seen[$key]=true;$ts=strtotime((string)$r['data'].' '.((string)($r['horario']??'00:00')))?:PHP_INT_MAX;$date=date('d/m/Y',strtotime((string)$r['data']));$weekday=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][(int)date('w',strtotime((string)$r['data']))]??'';$time=trim((string)($r['horario']??''));$time=$time!==''?substr($time,0,5):'';$culto=trim((string)($r['culto_nome']??''))?:'Culto';$dept=trim((string)($r['departamento_nome']??''));$func=trim((string)($r['funcao']??''));$label="{$weekday}, {$date}".($time!==''?" às {$time}":'')." — {$culto}".($dept!==''?" — {$dept}":'').($func!==''?" / {$func}":'');$out[]=['type'=>'confirmed_scale','id'=>$key,'item_id'=>$key,'escala_id'=>(string)$r['escala_id'],'voluntario_id'=>(string)$r['voluntario_id'],'igreja_id'=>(string)$r['igreja_id'],'culto_id'=>(string)($r['culto_id']??''),'data'=>(string)$r['data'],'label'=>$label,'sort_ts'=>$ts];}
    return$out;
}
function v1434_scale_row(string $itemId): ?array { try{$q=db()->prepare("SELECT ei.id item_id,ei.escala_id,ei.voluntario_id,ei.funcao,ei.status_confirmacao,e.data,e.igreja_id,e.culto_id,c.nome culto_nome,c.horario,d.nome departamento_nome,p.nome voluntario_nome,p.whatsapp FROM escala_itens ei JOIN escalas e ON BINARY e.id=BINARY ei.escala_id LEFT JOIN cultos c ON BINARY c.id=BINARY e.culto_id LEFT JOIN departamentos d ON BINARY d.id=BINARY e.departamento_id LEFT JOIN profiles p ON BINARY p.id=BINARY ei.voluntario_id WHERE BINARY ei.id=BINARY ? LIMIT 1");$q->execute([$itemId]);$r=$q->fetch(PDO::FETCH_ASSOC);return$r?:null;}catch(Throwable$e){return null;} }
function v1434_repertoire(array $r): array { try{return function_exists('v1421_same_day_repertoire')?v1421_same_day_repertoire($r):[];}catch(Throwable$e){return[];} }
function v1434_scale_list_text(array $scales,string $kind='scales'): string { $count=count($scales);$title=$kind==='music'?'🎵 *Escolha a escala para consultar o repertório:*':'📅 *Suas escalas confirmadas nos próximos 30 dias:*';$m=$title."\n\n";foreach(array_slice($scales,0,20)as$i=>$o)$m.='*'.($i+1).'* - '.$o['label']."\n";if($count>20)$m.="\n_Mostrando as 20 primeiras._\n";$m.="\n➡️ Responda com o *número da escala*.\nDigite *MENU* para voltar ao menu principal.";return$m; }
function v1434_detail_text(array $r): string { $date=!empty($r['data'])?date('d/m/Y',strtotime((string)$r['data'])):'—';$time=trim((string)($r['horario']??''));$time=$time!==''?substr($time,0,5):'—';$m="📅 *Detalhes da sua escala*\n\n📋 ".(($r['culto_nome']??'')?:'Culto')."\n📅 {$date}\n🕒 {$time}\n⛪ ".(($r['departamento_nome']??'')?:'Ministério')." — ".(($r['funcao']??'')?:'Função');$songs=v1434_repertoire($r);if($songs){$m.="\n\n🎵 *Repertório do dia:*";foreach($songs as$i=>$song){$t=trim((string)($song['titulo']??''));if($t==='')continue;$a=trim((string)($song['artista']??''));$tom=trim((string)($song['tom']??''));$m.="\n".($i+1).". *{$t}*".($a!==''?" — {$a}":'').($tom!==''?" (Tom: {$tom})":'');}}else{$m.="\n\n🎵 _Ainda não há repertório cadastrado para esse culto._";}$m.="\n\n📄 *1* - Receber o PDF da escala completa desse dia\n📅 *2* - Voltar às minhas próximas escalas\n🏠 *0* - Voltar ao MENU";return$m; }
function v1434_show_home(string $sender,array $profiles,?array $session=null): bool { if(function_exists('v1311p_delete_session')&&$session)v1311p_delete_session($session);if(function_exists('v1311p_save_session'))v1311p_save_session($sender,$profiles,'vmenu_home',[],null,null,null);$ig=v1434_igreja_id($profiles);return function_exists('v1311p_send')?v1311p_send($sender,$ig,v1434_home_text(),'volunteer_home_menu'):false; }
function v1434_show_scales(string $sender,array $profiles,string $kind='scales',?array $session=null): bool { $scales=v1434_confirmed_scales($profiles);$ig=v1434_igreja_id($profiles);if(!$scales){if($session&&function_exists('v1311p_delete_session'))v1311p_delete_session($session);if(function_exists('v1311p_save_session'))v1311p_save_session($sender,$profiles,'vmenu_home',[],null,null,null);$msg="📅 Você não possui escalas *confirmadas* nos próximos 30 dias.\n\n".v1434_home_text();return v1311p_send($sender,$ig,$msg,'volunteer_no_confirmed_scales');}$state=$kind==='music'?'vmenu_music':'vmenu_scales';if(function_exists('v1311p_save_session'))v1311p_save_session($sender,$profiles,$state,array_slice($scales,0,20),null,null,$session);return v1311p_send($sender,$ig,v1434_scale_list_text($scales,$kind),'volunteer_confirmed_scales',['count'=>count($scales),'kind'=>$kind]); }
function v1434_pdf_schema(): void { try{db()->exec("CREATE TABLE IF NOT EXISTS whatsapp_scale_pdf_tokens(id VARCHAR(36) NOT NULL PRIMARY KEY,token_hash CHAR(64) NOT NULL UNIQUE,voluntario_id VARCHAR(36) NOT NULL,igreja_id VARCHAR(36) NOT NULL,escala_id VARCHAR(36) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at DATETIME NOT NULL,KEY idx_wpdf_exp(expires_at),KEY idx_wpdf_scale(escala_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}catch(Throwable$e){} }
function v1434_pdf_link(array $r): ?string { v1434_pdf_schema();try{$raw=bin2hex(random_bytes(24));$hash=hash('sha256',$raw);db()->prepare("DELETE FROM whatsapp_scale_pdf_tokens WHERE expires_at<NOW()")->execute();db()->prepare("INSERT INTO whatsapp_scale_pdf_tokens(id,token_hash,voluntario_id,igreja_id,escala_id,created_at,expires_at) VALUES(?,?,?,?,?,NOW(),DATE_ADD(NOW(),INTERVAL 7 DAY))")->execute([uuid4(),$hash,(string)$r['voluntario_id'],(string)$r['igreja_id'],(string)$r['escala_id']]);return'https://escala.isaacanthony.com.br/api/scale-day-pdf-v1434.php?t='.$raw;}catch(Throwable$e){if(function_exists('v1311p_trace'))v1311p_trace('v1434_pdf_token_error',['message'=>substr($e->getMessage(),0,240)]);return null;} }
function v1434_send_pdf(string $sender,array $r): bool { $url=v1434_pdf_link($r);$ig=(string)($r['igreja_id']??'');if(!$url)return v1311p_send($sender,$ig,"⚠️ Não consegui preparar o PDF agora. Tente novamente em alguns instantes.",'pdf_prepare_failed');$date=!empty($r['data'])?date('d-m-Y',strtotime((string)$r['data'])):date('d-m-Y');$caption="📄 Escala completa — ".(($r['culto_nome']??'')?:'Culto')." — {$date}";$mediaOk=false;try{$base=rtrim(v1424_cfg('evolution_url',$ig),'/');$key=v1424_cfg('evolution_api_key',$ig);$instance=v1424_cfg('evolution_instance',$ig);$number=v1424_phone($sender);if($base!==''&&$key!==''&&$instance!==''&&strlen($number)>=10){$endpoint=$base.'/message/sendMedia/'.rawurlencode($instance);$headers=['Content-Type: application/json','apikey: '.$key];$payload=['number'=>$number,'mediatype'=>'document','mimetype'=>'application/pdf','caption'=>$caption,'media'=>$url,'fileName'=>'escala-'.$date.'.pdf'];$res=v1424_http_json($endpoint,$payload,$headers);if(empty($res['ok'])&&((int)($res['status']??0)===0||(int)($res['status']??0)>=500)){usleep(500000);$res=v1424_http_json($endpoint,$payload,$headers);}$mediaOk=!empty($res['ok']);try{if(function_exists('log_whatsapp'))log_whatsapp('whatsapp_pdf',$number,$caption,$res,$ig,['scale_id'=>$r['escala_id'],'pdf_url'=>$url]);}catch(Throwable$e){}}}catch(Throwable$e){}if($mediaOk)return true;return v1311p_send($sender,$ig,"📄 *PDF da escala completa*\n\nSe o arquivo não abrir automaticamente, toque no link abaixo para baixar:\n{$url}\n\n_O link fica disponível por 7 dias._",'pdf_link_fallback',['escala_id'=>$r['escala_id']]); }
function v1434_handle_menu_session(array $session,array $profiles,string $sender,string $text): bool { $t=function_exists('mb_strtolower')?mb_strtolower(trim($text),'UTF-8'):strtolower(trim($text));$state=(string)($session['state']??'');if(function_exists('v1311p_is_menu_word')&&v1311p_is_menu_word($t)){if(function_exists('v1311p_collect_options')){$pending=v1311p_collect_options($profiles);if($pending){v1311p_delete_session($session);return v1311p_show_menu($sender,$profiles,$pending,null);}}return v1434_show_home($sender,$profiles,$session);}if($state==='vmenu_home'){if($t==='1')return v1434_show_scales($sender,$profiles,'scales',$session);if($t==='2')return v1434_show_scales($sender,$profiles,'music',$session);return v1311p_send($sender,v1434_igreja_id($profiles),"🤔 Escolha *1* ou *2*.\n\n".v1434_home_text(),'volunteer_home_invalid');}if($state==='vmenu_scales'||$state==='vmenu_music'){$opts=json_decode((string)($session['options_json']??''),true);if(!is_array($opts))$opts=[];if(!preg_match('/^\d{1,2}$/',$t))return v1311p_send($sender,v1434_igreja_id($profiles),"🤔 Responda somente com o *número da escala*.\n\n".v1434_scale_list_text($opts,$state==='vmenu_music'?'music':'scales'),'volunteer_scale_select_invalid');$idx=(int)$t-1;if($idx<0||$idx>=count($opts))return v1311p_send($sender,v1434_igreja_id($profiles),"⚠️ Essa opção não existe. Escolha um número entre *1 e ".count($opts)."*.",'volunteer_scale_select_range');$r=v1434_scale_row((string)$opts[$idx]['item_id']);if(!$r||($r['status_confirmacao']??'')!=='confirmado'){return v1434_show_scales($sender,$profiles,$state==='vmenu_music'?'music':'scales',$session);}v1311p_save_session($sender,$profiles,'vmenu_detail',$opts,'confirmed_scale',(string)$r['item_id'],$session);return v1311p_send($sender,(string)$r['igreja_id'],v1434_detail_text($r),'volunteer_scale_detail',['escala_id'=>$r['escala_id'],'escala_item_id'=>$r['item_id']]);}if($state==='vmenu_detail'){$r=v1434_scale_row((string)($session['selected_id']??''));if(!$r){v1311p_delete_session($session);return v1434_show_home($sender,$profiles,null);}if($t==='1')return v1434_send_pdf($sender,$r);if($t==='2')return v1434_show_scales($sender,$profiles,'scales',$session);if($t==='0')return v1434_show_home($sender,$profiles,$session);return v1311p_send($sender,(string)$r['igreja_id'],"🤔 Escolha *1* para receber o PDF, *2* para ver as próximas escalas ou *0* para voltar ao MENU.\n\n".v1434_detail_text($r),'volunteer_detail_invalid');}return false; }
